#ifndef RTW_HEADER_MPPTSolarChargeControllerModel_acc_types_h_
#define RTW_HEADER_MPPTSolarChargeControllerModel_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_MPPTSolarChargeControllerModel_T_
P_MPPTSolarChargeControllerModel_T ;
#endif
